included: # paths to include during linting. `--path` is ignored if present.
  - localview
  - localviewTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - ThirdPartyLib

line_length: 120
